// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Regenerate: npm run content:generate
//
// Every lucide icon named by the practice-area content, imported explicitly so
// the bundler can drop the ~1,950 that are not used. See the generator for why
// this is not lucide-react's DynamicIcon.

import type { LucideIcon } from "lucide-react";
import {
  Baby,
  BadgeCheck,
  Banknote,
  Briefcase,
  Building,
  Building2,
  Car,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  Copyright,
  Cpu,
  Fence,
  FileCheck,
  FilePen,
  FileSearch,
  FileSignature,
  FileText,
  Flag,
  Gavel,
  GraduationCap,
  Hammer,
  HandCoins,
  Handshake,
  HardHat,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  House,
  IdCard,
  Key,
  KeyRound,
  LandPlot,
  Landmark,
  LifeBuoy,
  Lightbulb,
  Lock,
  Megaphone,
  MessagesSquare,
  Pill,
  Plane,
  Scale,
  ScrollText,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Stethoscope,
  TriangleAlert,
  UserCheck,
  Users,
  UsersRound,
} from "lucide-react";

export const PRACTICE_AREA_ICONS: Record<string, LucideIcon> = {
  baby: Baby,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  car: Car,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  cloud: Cloud,
  copyright: Copyright,
  cpu: Cpu,
  fence: Fence,
  "file-check": FileCheck,
  "file-pen": FilePen,
  "file-search": FileSearch,
  "file-signature": FileSignature,
  "file-text": FileText,
  flag: Flag,
  gavel: Gavel,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  "hand-coins": HandCoins,
  handshake: Handshake,
  "hard-hat": HardHat,
  "heart-crack": HeartCrack,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  house: House,
  "id-card": IdCard,
  key: Key,
  "key-round": KeyRound,
  "land-plot": LandPlot,
  landmark: Landmark,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  lock: Lock,
  megaphone: Megaphone,
  "messages-square": MessagesSquare,
  pill: Pill,
  plane: Plane,
  scale: Scale,
  "scroll-text": ScrollText,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  siren: Siren,
  stethoscope: Stethoscope,
  "triangle-alert": TriangleAlert,
  "user-check": UserCheck,
  users: Users,
  "users-round": UsersRound,
};
